name: Doge
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.3
environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: 3.27.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
