name: build

on:
  workflow_call:
    inputs:
      path:
        default: 'pubspec.yaml'
        required: true
        type: string
      target:
        required: true
        type: string
        description: "Build target (android, ios, linux, macos, windows, web)"
      build-args:
        required: true
        type: string
        description: "Flutter Building Args"
      platform:
        required: true
        type: string
        description: "Running Platform"


jobs:
  ready:
    uses: ./.github/workflows/get-info.yml
    with:
      path: ${{ inputs.path }}
      target: ${{ inputs.target }}

  build:
    runs-on: ${{ inputs.platform }}
    needs:
      - ready
    steps:
      - uses: actions/checkout@v4
      - if: matrix.platform == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
        shell: bash
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      -
        run: flutter ${{ inputs.build-args }}
      - run: |
          RELEASE_NAME="${{ needs.ready.outputs.name_lower }}"
          PREFIX="${{ needs.ready.outputs.release }}"
          BIN="$RELEASE_NAME-${{ needs.ready.outputs.version }}-${{ inputs.target }}.zip"

          echo $RELEASE_NAME
          echo $PREFIX
          echo $BIN
        shell: bash