name: build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  ready-version:
    needs:
      - pre
    uses: ./.github/workflows/get-version.yml
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}

  ready-name:
    needs:
      - pre
    uses: ./.github/workflows/get-name.yml
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}

  ready-path:
    needs:
      - pre
      - ready-name
    uses: ./.github/workflows/get-path.yml
    with:
      target: ${{ needs.pre.outputs.target }}
      name: ${{ needs.ready-name.outputs.name_lower }}

  build-mobile:
    runs-on: macos-latest
    needs:
      - pre
      - ready-version
      - ready-name
      - ready-path
    strategy:
      matrix:
        target: [ios, android]
        include:
          - target: ios
            build: "build ios --release --no-codesign"
          - target: android
            build: "build apk --release"

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      - 
        name: Build for ${{ matrix.target }}
        run:
          flutter ${{ matrix.build }}
        shell: bash
      - 
        if: matrix.target == 'android'
        run: |
          RELEASE_NAME="${{ needs.ready-name.outputs.name_lower }}"
          PREFIX="{{ needs.ready-path.outputs.release }}"
          EXTENSION="${PREFIX##*.}"
          BIN="$RELEASE_NAME-${{ needs.ready-version.outputs.version }}-${{ matrix.target }}.$EXTENSION"

          mv "{{ needs.ready-path.outputs.release }}" $BIN
          gh release upload ${{ needs.ready-version.outputs.version }} $BIN --clobber

        shell: bash
        name: Upload
      - 
        if: matrix.target == 'ios'
        run: |
          RELEASE_NAME="${{ needs.ready-name.outputs.name_lower }}"
          PREFIX="{{ needs.ready-path.outputs.release }}"
          EXTENSION="${PREFIX##*.}"
          BIN="$RELEASE_NAME-${{ needs.ready-version.outputs.version }}-${{ matrix.target }}"

          mv "{{ needs.ready-path.outputs.release }}" $BIN.$EXTENSION
          mkdir -p dist
          hdiutil create -volname "$BIN" -srcfolder "$BIN.$EXTENSION" -ov -format UDZO "$BIN.dmg"
          gh release upload ${{ needs.ready-version.outputs.version }} $BIN.dmg --clobber
        shell: bash
        name: Upload