name: build-linux

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"
  TARGET: "linux"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-linux.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
      target: ${{ env.TARGET }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  ready:
    needs:
      - pre
    uses: ./.github/workflows/get-info.yml
    with:
      path: ${{ needs.pre.outputs.pubspec }}
      target: ${{ needs.pre.outputs.target }}

  build-linux:
    runs-on: ubuntu-20.04
    needs:
      - pre
      - ready
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - 
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      -
        run: flutter build ${{ needs.pre.outputs.target }}
      - 
        run: |
          RELEASE_NAME="${{ needs.ready.outputs.name_lower }}"
          PREFIX="${{ needs.ready.outputs.release }}"
          BIN="$RELEASE_NAME-${{ needs.ready.outputs.version }}-${{ needs.pre.outputs.target }}.zip"

          cd $PREFIX && zip -r $BIN ./*
          gh release upload ${{ needs.ready.outputs.version }} $BIN --clobber
        shell: bash
        name: Upload

