name: build-macos

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"
  TARGET: "macos"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-legacy.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
      target: ${{ env.TARGET }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  ready:
    needs:
      - pre
    uses: ./.github/workflows/get-info.yml
    with:
      path: ${{ needs.pre.outputs.pubspec }}
      target: ${{ needs.pre.outputs.target }}

  build-macos:
    runs-on: macos-latest
    needs:
      - pre
      - ready
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      -
        run: flutter build ${{ needs.pre.outputs.target }}
      - 
        run: |
          RELEASE_NAME="${{ needs.ready.outputs.name_lower }}"
          PREFIX="${{ needs.ready.outputs.release }}"
          EXTENSION="${PREFIX##*.}"
          BIN="$RELEASE_NAME-${{ needs.ready.outputs.version }}-${{ needs.pre.outputs.target }}"

          mv "${{ needs.ready.outputs.release }}" $BIN.$EXTENSION
          hdiutil create -volname "$BIN" -srcfolder "$BIN.$EXTENSION" -ov -format UDZO "$BIN.dmg"
          gh release upload ${{ needs.ready.outputs.version }} $BIN.dmg --clobber
        shell: bash
        name: Upload