name: ci

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/ci.yml"
      - "pubspec.yaml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"
  ready-version:
    needs:
      - pre
    uses: ./.github/workflows/get-version.yml
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}
  tag:
    needs:
      - ready-version
    uses: ./.github/workflows/create-tag.yml
    with:
      version: ${{ needs.ready-version.outputs.version }}
  release:
    needs:
      - tag
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ needs.tag.outputs.tag }}
      note: "add release for ${{ needs.tag.outputs.tag }}"