name: get-path
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: "Build target (android, ios, linux, macos, windows, web)"
      name:
        required: true
        type: string
        description: "Application name"
    outputs:
      release:
        description: "Platform-specific release path"
        value: ${{ jobs.resolve.outputs.release }}

jobs:
  resolve:
    runs-on: ubuntu-24.04
    outputs:
      release: ${{ steps.get-release.outputs.release }}
    steps:
      - 
        id: get-release
        run: |
          case $PLATFORM in
            "android")
              release="build/app/outputs/flutter-apk/app-release.apk"
              ;;
            "ios")
              release="build/ios/ipa/$APP_NAME-release.ipa"
              ;;
            "linux")
              release="build/linux/x64/release/bundle"
              ;;
            "macos")
              release="build/macos/Build/Products/Release/$APP_NAME.app"
              ;;
            "windows")
              release="build/windows/x64/runner/Release"
              ;;
            "web")
              release="build/web"
              ;;
            *)
              echo "Error: Unsupported target $PLATFORM"
              exit 1
              ;;
          esac
          echo release=$release >> $GITHUB_OUTPUT
        shell: bash
        env:
          PLATFORM: ${{ inputs.target }}
          APP_NAME: ${{ inputs.name }}